### ISSUE TITLE
Account removal in forums and on site

### ISSUE THREAD

**Issue by Shumatsu** [LISTEN-moe/feedback#12]
**Type:** enhancement
**Description:** Currently there's no way to terminate site or forum account.

- Priority this should have – please be realistic and elaborate if possible: low

**Comment by iCrawl** [comment]
Account deletion will probably never be a thing because fucking with database relations is a big no-no.
Something similar in terms of facebook will be in place, disabling your account.
For now you'll have to remove sensitive data and just don't use the account anymore.

**Comment by DrizztFR** [comment]
Hello. I wanted to open a similar issue. 

Please note that GPDR is now active in Europe and you have the legal obligation to provide this option (and to be able to erase personal data from your database) as long as your site is accessible from Europe.

I won't bother you with it, but other people could. Maybe you should reopen the issue and ask for help on the topic.

Thanks.
