### ISSUE TITLE
More human readable errors

### ISSUE THREAD

**Issue by onestay** [LISTEN-moe/feedback#16]
**Type:** Enhancement
**Description:** Replace error codes with human readable errors

**Further details:**
Well, to be honest, the errors are totally human readable and fine but it would be nice if instead of something like this https://i.hikari.moe/JvdzS.png something like this https://i.hikari.moe/VMWoL.png would pop up. Just a suggestion. Of course, this is low priority but it would create a better user exeperience in my opinion.

**Comment by iCrawl** [comment]
Already fixed in v4.
