### ISSUE TITLE
Restrict maximum length of songs played when there are no requests.

### ISSUE THREAD

**Issue by Shumatsu** [LISTEN-moe/feedback#18]
**Type:** Enhancement
**Description:** Limit the maximum length of songs played when no one has requested any song.

**Further details:** There's this "★NightcoreClarity - HBD VainZ  (≧▽≦)づ", which probably shouldn't be on the radio at all. This song is actually a few ClariS songs remixed and played one after another. It's probably 10 minutes or more. I believe it would be nice if songs played during idle time were maximum 4 minutes. It would help promote less known songs better.

- Priority this should have – please be realistic and elaborate if possible: low

**Comment by Pitu** [comment]
This won't happen, autodj will always be random.
On another note, that song shouldn't be there, that's true.
