### ISSUE TITLE
Sorting songs in "Uploaded songs" page

### ISSUE THREAD

**Issue by Shumatsu** [LISTEN-moe/feedback#19]
**Type:** Enhancement
**Description:** Sorting of uploaded songs by status (All/Approved/Denied/Waiting).

**Further details:** I believe this change would make uploading neater, as uploaders wouldn't need to look through entire list of uploads to check songs' status.

- Priority this should have – please be realistic and elaborate if possible: low

**Comment by Pitu** [comment]
This has already been implemented in v4.
