### ISSUE TITLE
Request and favorite songs from "uploaded songs"

### ISSUE THREAD

**Issue by iizu** [LISTEN-moe/feedback#2]
Type: feature request
Priority: low
Description:
There should be a way to request and favorite songs from the "uploaded songs" tab. Similar to how there is a play and star button when you search for a song normally. Possibly splitting up approved songs and ones that are still pending to streamline and allow non-uploaded songs to not receive this feature.

slapped together possible example:
![test2](https://cloud.githubusercontent.com/assets/27186547/25778419/1b820a30-32cb-11e7-8e1b-f2464d360a9a.png)

**Comment by Pitu** [comment]
You can now achieve this by going to Profile -> Uploads. We won't add the request button on the upload section for now.
