### ISSUE TITLE
Limiting ammount on single "Uploaded songs" page

### ISSUE THREAD

**Issue by Shumatsu** [LISTEN-moe/feedback#20]
**Type:** enhancement
**Description:** Making "Uploaded songs" similar to request page by limiting ammount of visible songs per page to one of set ammounts.

**Further details:** As time passes, the list of uploaded songs can grow quite long, especially so if song has an elaborate comment.

- Priority this should have – please be realistic and elaborate if possible: low

**Comment by Pitu** [comment]
This has already been implemented in v4
