### ISSUE TITLE
Password reset email doesn't provide username, can't login with email address, and no login error feedback

### ISSUE THREAD

**Issue by Danktuary** [LISTEN-moe/feedback#23]
**Type:** Enhancement
**Description:** The email you get upon requesting a password reset ([this](https://i.imgur.com/aKD8Y4y.png)) doesn't include the username you used to sign up. In addition, it's currently not possible to login with your email address, and no feedback is provided for the user when they provide invalid credentials.

**Further details:** I completely forgot my login info when I tried logging in yesterday (haven't logged in for a while), so I requested a password reset yesterday, and I was able to reset my password just fine. However, the email didn't tell the username I used to sign up.

I understand that some people don't like providing that sort of info in emails for whatever reason, but the issue is that you can only login to listen.moe with your username. It's pretty easy to get locked out due to this. There's also no error message being displayed upon failure (due to wrong password, trying to use an email as the username, etc.), so it's a bit hard to tell if I gave invalid input or if the site just isn't working at all.

- Browser: Google Chrome 62.0 
- Priority this should have – please be realistic and elaborate if possible: Low

**Comment by Pitu** [comment]
This was just fixed a few seconds ago by letting people log in with their email as well. Thanks for reporting it!
