### ISSUE TITLE
After some time, websocket seems to break, causing music to stop

### ISSUE THREAD

**Issue by Porkepix** [LISTEN-moe/feedback#27]
*Please describe the problem you are having in as much detail as possible:**
WebSocket break after some time, causing music to stop

**Further details:**
- Browser version: Firefox stable 65.0.1; but I think problem exist for quite some time.
- Operating system: ArchLinux
- Priority this should have – please be realistic and elaborate if possible:
Well, it breaks listening the radio after some time, so I would definitely not say low and would argue for high, medium at the very least.

Here's the error message user can find in browser's console
```
Websocket connection closed. Reconnecting... 
close { target: WebSocket, isTrusted: true, wasClean: true, code: 1001, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
chunk--app.b32975aa.chunk.js:1:209237
```

Issue also seems to affect the addon.

**Comment by Pitu** [comment]
This is partially solved in the beta branch releasing early next month, so I'll go ahead and close the issue. You can check it on [https://beta.listen.moe](https://beta.listen.moe) and if it keeps happening to you, please feel free to reopen it.

**Comment by Porkepix** [comment]
@Pitu Tested, it just happened right now :(
It might have take more time than before (but need more observations for that), but it doesn't look like it's solved :(

**Comment by Porkepix** [comment]
@Pitu I can't see the websocket above anymore, but as commented above, stream is still being interrupted after some play time. I didn't reopened the issue back then because I don't have permissions to do so.
Do you want me to opened a new issue regarding these interruptions?

**Comment by Pitu** [comment]
Unfortunately this is most likely a you problem. The websocket and stream have been working fine and there is no problem with them.
It's most likely your internet connection, the region you are in or some other external factor :(

**Comment by Porkepix** [comment]
> Unfortunately this is most likely a you problem. The websocket and stream have been working fine and there is no problem with them.
> It's most likely your internet connection, the region you are in or some other external factor :(

@Pitu Well, I experienced it from various computer and OS, for now a long time, including excellent connections with optic fiber, so I would be quite surprised for this to be the cause of the issue. Not to mention listen.moe is the only one website I've got such issue, and that the issue only happen with the website or the browser extension: Android application or when I used it the direct url to stream in a multimedia player suffered no such issue.

Considering all the above, it sems more than likely it is an issue with the Web player, the browser (Firefox), and maybe interactions with some of my browser extensions (the list is quite short: HTTPS everywhere, uBlock origin, uMatrix [correctly configured, what is necessary is allowed] and Decentraleyes) as those are the only common points with all the times I got the issue, from Linux, Mac or Windows computer, using Wired or Wi-Fi, over optic fiber or DSL connections, having absolutely no issue with any other media service or listen.moe's own applications/direct streams.

Unfortunately I don't have the Web development knowledges, and the code is anyway not open to debug this by myself, by this is honestly very annoying to have music playing and somehow being interrupted very regularly, and have to go at the player, stop it and restart it to have the music come back :/

**Comment by Porkepix** [comment]
If this may help, here's a screenshot of the browser console, even if I'm not sure anything useful can be found from this.
The yellow lines are the ones that appears when click stop and play to get the music back after the problem happens.

![Screenshot from 2020-04-08 09-25-34](https://user-images.githubusercontent.com/709500/78756475-2829fc80-797b-11ea-8255-35b0c3b82c41.png)
