### ISSUE TITLE
Bug where the favorites page says you have a song in the queue but you don't

### ISSUE THREAD

**Issue by kosterlitz** [LISTEN-moe/feedback#4]
**Type:** Bug
**Priority:** low
**Description:**
When a song is requested from the "favorites" page, the little bubble that says "_n_ songs in queue, there are _m_ songs until your next song", continues to say your song is playing next even after it has played, and even though the "request a song" page correctly shows that you do not have a song in the queue.

**Comment by Pitu** [comment]
I remember this bug 😅 , hopefully it will go away on it's own on the v4 rewrite.
