### ISSUE TITLE
Double play bug?

### ISSUE THREAD

**Issue by kosterlitz** [LISTEN-moe/feedback#7]
**Type:** Bug
**Description:**  I am pretty sure that when I requested ME!ME!ME! today, it played twice.

**Further details:** (1) second play DID consume one of my requests and increase the displayed size of the queue (I think.). (2) second play DID NOT cause the song to appear in the list of previously played songs twice.

**Comment by Pitu** [comment]
Can confirm the system processed your request twice https://lolisafe.moe/Hio3UPaO.png
I'm gonna dig and see if I can find the cause, thanks!
