### ISSUE TITLE
Better titles for fields in songlist

### ISSUE THREAD

**Issue by Shumatsu** [LISTEN-moe/feedback#9]
**Type:** Enhancement
**Description:** Currently the fields in songlist have titles like 'Anime', 'Artist', 'Actions'. Those show up on mouseover, so they could be a little bit more useful, for example title for Artist could show kanji/romanji writing, same for track title.

**Further details:**

- Browser: It's all HTML, so it's independent of browser.
- Priority this should have – please be realistic and elaborate if possible: low

**Comment by Pitu** [comment]
While I think the song list needs an overhaul and the tooltips right now are useless, I would probably not put the translations in a tooltip since it's not possible to select/copy the text inside.

**Comment by Pitu** [comment]
Tooltips updated with actual tooltips instead of `Anime`, `Artist` and `Cooldown`
